[package]
name = "bazel-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.73"
axum = "0.6.20"
rust-s3 = "0.33.0"
serde = { version = "1.0.183", features = ["derive"] }
tokio = { version = "1.30.0", features = ["full"] }
tonic = "0.9.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["tracing-log", "fmt"] }
